Fix/windows path resolve issues
tobiasdiez/nuxt-graphql-server pull request #68
Opened 2023-08-11 19:44 UTC by sduduzog

- Addresses https://github.com/tobiasdiez/nuxt-graphql-server/issues/28 by inlining virtual files
- Possibly fixes https://github.com/nuxt/nuxt/issues/19453

2023-08-27 14:12 UTC, tobiasdiez requested changes

2023-08-27 14:12 UTC, tobiasdiez commented on src/module.ts
> +    setAlias(nuxt, '#graphql/schema', schemaPath)
This line is a duplication of line 66. Is this on purpose?

2023-08-27 14:12 UTC, tobiasdiez commented on src/module.ts
> +    // no need to add to nuxt.d.ts as all types are exported from this alias
I don't really understand this comment. Can you expand on it please?

Maybe also move it down to the `prepare:types` hook to describe why we only add the schema and not also resolver to types.

2023-08-27 14:12 UTC, tobiasdiez commented on src/module.ts
> +  nuxt.hook('nitro:config', nitroConfig => {
Is there a reason why this is change is also needed in production? Please also keep the reference to https://github.com/nuxt/nuxt/issues/19453.

2023-09-03 07:26 UTC, tobiasdiez commented
@sduduzog now that you other PR is merged, it would be nice if you could have a look at my comments above (and merge in the latest changes)!

2023-09-06 18:42 UTC, sduduzog commented
@tobiasdiez  sorry for keeping this held up for so long. I haven't had time to take a look back at it yet. And with the number of comments on the PR, I really want to make it more granular and specific.

Updates to it will be to move anything that has nothing to do with the PR title to another instead.

That will make our discussions precise I believe

2023-09-07 05:46 UTC, tobiasdiez commented
No worries! Take your time...

But I don't think the PR is to involved. Once you rebase, it should only contain a couple of changes - so no need to create a new PR in my opinion (but of course its up to you in the end).

2023-09-11 00:28 UTC, tobiasdiez commented
Does this PR helps with https://github.com/tobiasdiez/nuxt-graphql-server/issues/71?

@sduduzog I can also take over from here if you are busy the next days. In this case, please shortly reply to my questions above. Thanks!

2023-09-11 09:25 UTC, sduduzog commented on src/module.ts
> +  nuxt.hook('nitro:config', nitroConfig => {
The previous implementation of 'setAlias' added aliases to both vite and nitro. With this change, types are only exposed to nitro. That's where we need access to resolver types, including the schema

2023-09-11 09:46 UTC, sduduzog commented on src/module.ts
> +    setAlias(nuxt, '#graphql/schema', schemaPath)
nope, fixing

2023-09-11 10:10 UTC, sduduzog commented
@tobiasdiez While checking out the questions to refresh myself of the context, I ended up resolving some, maybe all pr queries.

Unit tests passing and hopefully the CI will be happy too

2023-09-11 18:20 UTC, awdr74100 commented
This PR does fix #71. Excellent! Hope it can be released soon.

2023-09-14 10:16 UTC, awdr74100 commented
Hi @tobiasdiez, can you please confirm this PR? This module is of great help to the project I am currently working on, thank you very much!

2023-09-15 14:38 UTC, tobiasdiez approved these changes
Thanks again!

I mark this as a breaking change, since it's now no longer possible to import the schema from the vue side, but that's also not very important.

2023-09-15 14:42 UTC, sduduzog commented
Naturally, I'll be occasionally checking issues to try help with any issues we could have introduced.

2023-09-15 14:43 UTC, merged